aws:
- account_id: '102096708990'
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - af-south-1
  - ap-south-1
  - ap-southeast-3
  - ap-east-1
  - us-gov-west-1
  - sa-east-1
  - us-gov-east-1
  - me-south-1
  - eu-north-1
  - eu-south-1
  - eu-west-3
  - eu-west-2
  - eu-west-1
  - eu-central-1
  - ap-northeast-1
  - ca-central-1
  - ap-southeast-2
  - ap-southeast-1
  - ap-northeast-3
  - ap-northeast-2
  type: account
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
